# Generated by Django 5.1.2 on 2024-12-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagent_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReagentSalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Химическая формула"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Полное название"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Соль",
                "verbose_name_plural": "Соли",
            },
        ),
        migrations.RemoveField(
            model_name="solution",
            name="salt",
        ),
        migrations.CreateModel(
            name="ReagentSaltSolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "density",
                    models.FloatField(verbose_name="Плотность раствора, г/см³"),
                ),
                (
                    "salt_consumption",
                    models.FloatField(verbose_name="Расход соли, кг/м³"),
                ),
                (
                    "water_consumption",
                    models.FloatField(verbose_name="Расход воды, л/м³"),
                ),
                (
                    "salt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solutions",
                        to="reagent_db.reagentsalt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раствор соли",
                "verbose_name_plural": "Растворы солей",
                "ordering": ["salt", "density"],
            },
        ),
        migrations.DeleteModel(
            name="Salt",
        ),
        migrations.DeleteModel(
            name="Solution",
        ),
    ]
