# Generated by Django 5.1.2 on 2024-12-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reagent_db",
            "0002_reagentsalt_remove_solution_salt_reagentsaltsolution_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrosionInhibitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("type", models.CharField(max_length=100, verbose_name="Тип")),
                ("application", models.TextField(verbose_name="Применение")),
            ],
            options={
                "verbose_name": "Ингибитор коррозии",
                "verbose_name_plural": "Ингибиторы коррозии",
            },
        ),
        migrations.CreateModel(
            name="ScaleInhibitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("type", models.CharField(max_length=100, verbose_name="Тип")),
                ("application", models.TextField(verbose_name="Применение")),
            ],
            options={
                "verbose_name": "Ингибитор солеотложений",
                "verbose_name_plural": "Ингибиторы солеотложений",
            },
        ),
        migrations.CreateModel(
            name="Surfactant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("type", models.CharField(max_length=100, verbose_name="Тип")),
                ("application", models.TextField(verbose_name="Применение")),
            ],
            options={
                "verbose_name": "ПАВ",
                "verbose_name_plural": "ПАВы",
            },
        ),
    ]
