# Generated by Django 5.1.2 on 2024-12-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagent_db", "0003_corrosioninhibitor_scaleinhibitor_surfactant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surfactant",
            options={"verbose_name": "ПАВ", "verbose_name_plural": "ПАВ"},
        ),
        migrations.AlterField(
            model_name="surfactant",
            name="type",
            field=models.CharField(
                choices=[
                    ("Анионный ПАВ", "Анионный ПАВ"),
                    ("Катионный ПАВ", "Катионный ПАВ"),
                    ("Неионный ПАВ", "Неионный ПАВ"),
                    (
                        "Смесь анионных и катионных ПАВ",
                        "Смесь анионных и катионных ПАВ",
                    ),
                    (
                        "Смесь анионных и неионнных ПАВ",
                        "Смесь анионных и неионнных ПАВ",
                    ),
                ],
                max_length=100,
                verbose_name="Тип ПАВ",
            ),
        ),
    ]
