# Generated by Django 5.1.2 on 2024-12-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagent_db", "0004_alter_surfactant_options_alter_surfactant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightingAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Минерал", "Минерал"),
                            ("Осадочная порода", "Осадочная порода"),
                        ],
                        max_length=100,
                        verbose_name="Тип материала",
                    ),
                ),
                ("application", models.TextField(verbose_name="Применение")),
            ],
            options={
                "verbose_name": "Утяжелитель",
                "verbose_name_plural": "Утяжелители",
            },
        ),
    ]
