# Generated by Django 5.1.2 on 2024-12-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagent_db", "0006_polymer"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Базовая жидкость", "Базовая жидкость"),
                            ("Специальная добавка", "Специальная добавка"),
                            ("Химический реагент", "Химический реагент"),
                        ],
                        max_length=100,
                        verbose_name="Тип",
                    ),
                ),
                ("application", models.TextField(verbose_name="Применение")),
            ],
            options={
                "verbose_name": "Прочий материал",
                "verbose_name_plural": "Прочие материалы",
            },
        ),
    ]
