# Generated by Django 5.1.2 on 2025-04-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagent_db", "0007_othermaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReagentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Тип реагента")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Тип реагента",
                "verbose_name_plural": "Типы реагентов",
            },
        ),
        migrations.AddField(
            model_name="reagentsaltsolution",
            name="max_viscosity",
            field=models.FloatField(
                default=1.0, verbose_name="Максимальная вязкость раствора, мПа·с"
            ),
        ),
        migrations.AddField(
            model_name="reagentsaltsolution",
            name="viscosity",
            field=models.FloatField(default=1.0, verbose_name="Вязкость, мПа·с"),
        ),
    ]
