version: '3.8'  # Явная версия для лучшей совместимости

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn rocksilencing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - wellkiller_network  # Объединяем сервисы в одну сеть

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Маппирование порта 443 для HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем директорию сертификатов как только для чтения
    depends_on:
      - web
    networks:
      - wellkiller_network  # Объединяем сервисы в одну сеть

volumes:
  static_volume:

networks:
  wellkiller_network:
    driver: bridge
