version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn rocksilencing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Добавляем маппинг порта 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем директорию сертификатов
    depends_on:
      - web
    networks:
      - rocksilencing_default

volumes:
  static_volume:

networks:
  rocksilencing_default:
    driver: bridge
