# rocksilencing/docker-compose.yml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn rocksilencing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    # Удалили зависимость от nginx, чтобы избежать циклической зависимости

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web  # Nginx зависит от web

volumes:
  static_volume:
