# Generated by Django 4.2.1 on 2024-11-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt',
            name='description',
            field=models.TextField(blank=True, help_text='Описание соли', null=True),
        ),
    ]
