# Generated by Django 5.1.2 on 2024-12-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="salt",
        ),
        migrations.DeleteModel(
            name="Salt",
        ),
        migrations.DeleteModel(
            name="Solution",
        ),
    ]
