# Generated by Django 5.1.2 on 2024-12-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_remove_solution_salt_delete_salt_delete_solution"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
