# Generated by Django 5.1.2 on 2024-12-23 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название дизайна"),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Месторождение",
                    ),
                ),
                (
                    "cluster",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Кустовая площадь",
                    ),
                ),
                (
                    "well",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Скважина"
                    ),
                ),
                (
                    "calc_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип/Варианты расчётов",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "kill_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Результаты калькулятора глушения",
                    ),
                ),
                (
                    "scale_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Результаты калькулятора солеотложений",
                    ),
                ),
                (
                    "expert_data",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Результаты экспертной системы",
                    ),
                ),
                (
                    "chosen_technology",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Выбранная технология",
                    ),
                ),
            ],
        ),
    ]
