# Generated by Django 5.1.2 on 2024-12-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expert_systema", "0001_initial"),
        ("reagent_db", "0007_othermaterial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technology",
            options={"verbose_name": "Технология", "verbose_name_plural": "Технологии"},
        ),
        migrations.AlterModelOptions(
            name="technologygroup",
            options={
                "verbose_name": "Группа технологий",
                "verbose_name_plural": "Группы технологий",
            },
        ),
        migrations.AddField(
            model_name="technology",
            name="corrosion_inhibitors",
            field=models.ManyToManyField(
                blank=True,
                to="reagent_db.corrosioninhibitor",
                verbose_name="Ингибиторы коррозии",
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примечания"),
        ),
        migrations.AddField(
            model_name="technology",
            name="other_materials",
            field=models.ManyToManyField(
                blank=True,
                to="reagent_db.othermaterial",
                verbose_name="Прочие компоненты",
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="polymers",
            field=models.ManyToManyField(
                blank=True, to="reagent_db.polymer", verbose_name="Полимеры"
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="reagent_salts",
            field=models.ManyToManyField(
                blank=True, to="reagent_db.reagentsalt", verbose_name="Соли"
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="scale_inhibitors",
            field=models.ManyToManyField(
                blank=True,
                to="reagent_db.scaleinhibitor",
                verbose_name="Ингибиторы солеотложений",
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Краткое название"
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="surfactants",
            field=models.ManyToManyField(
                blank=True, to="reagent_db.surfactant", verbose_name="ПАВ"
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="weighting_agents",
            field=models.ManyToManyField(
                blank=True, to="reagent_db.weightingagent", verbose_name="Утяжелители"
            ),
        ),
    ]
